[[rows]]
== Rows

In addition to creating cells, there are also a few other methods available to you to make documents easier.

=== Underlying API

To get access to the {apachePoi}[Apache POI] API for a given row, simply receive an argument to the `row` closure:

[source,groovy]
----
import org.apache.poi.xssf.usermodel.XSSFRow

ExcelBuilder.build {
    sheet {
        row { XSSFRow myRow ->
            //Modify myRow as needed
        }
    }
}
----

=== Defaults

You can apply default styling at the row level in addition to the sheet level. Styles that conflict with defaults at the sheet level will override.

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        defaultStyle [:]
        row {
            defaultStyle [:]
        }
    }
}
----

=== Header Row

It is possible to define a header row and assign an identifier to each cell for later use.

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        columns {
            column("Foo", "foo")
            column("Bar", "bar")
        }
    }
}
----

In future rows, you can do things like skip to a given column or reference that column in a formula. The first argument is assigned to the cell value and the second argument is the unique identifier.

=== Creating Rows

You can easily create rows with the following syntax:

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        //Empty row
        row {
        }

        //Values in cells A2, B2, C2
        row(1,2,3)

        //Empty row with height specified
        //Height can be a Short if you want to set the height in "twips"
        row([height: 10F] {
        }

        //Empty row
        row()
    }
}
----

To reference everything you can do in a row, see the section in the documentation on link:#rows[Rows].

=== Skipping Rows

It is very easy to skip any number of rows. See the following example:

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        row("A", "B", "C")
        skipRows(2)
        row("A", "B", "C")
    }
}
----

The above example will produce a sheet that looks something like this:

[width="50%"]
|=======
|  |A |B |C

|*1* |A |B |C
|*2* |  |  |
|*3* |  |  |
|*4* |A |B |C
|=======

=== Skipping Cells

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        row {
            cell("foo")
            skipCells(2)
            cell("bar")
        }
    }
}
----

The previous example will produce a document with "foo" in cell A1 and "bar" in D1.

==== Skipping to a column

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        columns {
            column("Foo", "foo")
            skipCells(1)
            column("Bar", "bar")
        }
        row {
            skipTo("bar")
            cell("C2")
        }
    }
}
----

The example above will put the text "C2" in cell C2.

WARNING: The `skipTo` method will set the cell index so the next cell call will output data into the desired cell. Subsequent cells will start from that index. View the example below:

[source,groovy]
----
ExcelBuilder.build {
    sheet {
        columns {
            column("Foo", "foo")
            skipCells(1)
            column("Bar", "bar")
        }
        row {
            cell("A2")
            cell("B2")
            skipTo("foo")
            cell("replaces A2")
        }
    }
}
----

The first call to `cell` sets the value to "A2". The `skipTo` call sets the index so the next call will set the cell value to "replaces A2".

[width="50%"]
|=======
|  |A |B |C

|*1* |Foo | |Bar
|*2* |replaces A2  |B2  |
|=======